name: Continuous_Integration_Testing

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - uses: eine/setup-msys2@v1
      with:
        update: true
        install: mingw-w64-x86_64-toolchain make mingw-w64-x86_64-cmake mingw-w64-bin_i686-mingw mingw-w64-x86_64-bc
    - name: build sumokoin
      run: make depends target=i686-linux-gnu -j2
      
