name: Continuous_Integration_Testing
on: [push, pull_request]

jobs:
  cross-build-32-bit-linux-on-xenial:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: remove bundled boost and gcc
      run: |
        sudo rm -rf /usr/local/share/boost
        sudo apt-get purge -y gcc-5
    - name: set apt conf
      run: |
        echo "Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
    - name: update apt
      run: |
        sudo apt-get install -y software-properties-common
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update
    - name: install sumokoin dependencies
      run: |
        sudo apt -y install dpkg-dev libc6-dev make g++-7-multilib g++7 gcc-7 bc autoconf automake libtool gperf libssl-dev cmake miniupnpc libunbound-dev libevent-dev graphviz doxygen pkg-config libsodium-dev libhidapi-dev libnorm-dev libusb-1.0-0-dev libpgm-dev libudev-dev libtool autoconf automake python libtinfo5
        sudo apt-get purge -y gcc-5
        sudo apt-get purge -y gcc
        sudo apt-get purge -y gcc-5-multilib
        sudo apt-get purge -y lib32gcc-5-dev
        sudo apt-get purge -y libx32gcc-5-dev
         sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 60 \
                         --slave /usr/bin/g++ g++ /usr/bin/g++-7        
    - name: build sumokoin
      run: make depends target=i686-linux-gnu  
