name: Continuous_Integration_Testing

on: [push, pull_request]

jobs:
  cross-build-32-bit-linux-on-bionic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: remove bundled boost
      run: sudo rm -rf /usr/local/share/boost
    - name: set apt conf
      run: |
        echo "Acquire::Retries \"3\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::http::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
        echo "Acquire::ftp::Timeout \"120\";" | sudo tee -a /etc/apt/apt.conf.d/80-custom
    - name: update apt
      run: sudo apt update
    - name: install sumokoin dependencies
      run: sudo apt -y install build-essential cmake libboost-all-dev miniupnpc automake g++-multilib lib32gcc-7-dev lib32g++ bc autoconf libtool gperf libunbound-dev libevent-dev graphviz doxygen libunwind8-dev pkg-config libssl-dev libzmq3-dev libsodium-dev libhidapi-dev libnorm-dev libusb-1.0-0-dev libpgm-dev ccache
    - name: build sumokoin
      run: make depends target=i686-linux-gnu
