name: continuous-integration/gh-actions/cli

on: [push, pull_request]

jobs:

  build-ubuntu:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: remove bundled boost
      run: sudo rm -rf /usr/local/share/boost
    - name: set apt conf
      run: |
        sudo apt-get purge -y gcc-5
